//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DopplerServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DopplerServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb://localhost:27017.
        /// </summary>
        public static string MongoConnectionString {
            get {
                return ResourceManager.GetString("MongoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messengerdatabase.
        /// </summary>
        public static string MongoDBName {
            get {
                return ResourceManager.GetString("MongoDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MongoUsers {
            get {
                return ResourceManager.GetString("MongoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52f3a0ab62df9eb33b9216fa7ca030ecb4060382b6c2dbdc5f9a075fa84435bb011c2a1b8df039447a9db2911f202d80e2fc823d969d8bf35af41e9f187356fb530fb8a8454db1c07262d3ca01c3a966aa7301dec1e9490320195f0102ab6189618786c6f02a2fce2cb6e97f2dbf349134256a51c78046b2a55189f507e4373b562ba7722e25765a4215885187544957366df599a829c83113d44547266796b9d800a00e471612675e788b374f4caa4e0f8f7d63060c1f8f2f9808427a378f84b203346d561523ecb225d0e37744db840346b4cccef1da6a4c1fcd265d1c315b8877cbb392da81a93672ef25b738f670e4251711c5f01ce6ea3883c1e81c7b6a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SecurityKey {
            get {
                return ResourceManager.GetString("SecurityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=DESKTOP-GNILB6P;Database=Doppler;Trusted_Connection=True;.
        /// </summary>
        public static string SQLServer {
            get {
                return ResourceManager.GetString("SQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://192.168.0.154:5001.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
